/**
 * Audit Service
 * Manages audit trail operations with mock/real API switching
 */

import { config } from '../lib/config';
import { endpoints } from '../lib/api';
import { simulateApiDelay } from '../hooks/useActions';
import type { AuditEntry } from '../types/index';

// Mock audit data
const mockAuditEntries: AuditEntry[] = [
  {
    id: '1',
    action: 'create',
    entityType: 'user',
    entityId: 'u123',
    userId: 'admin1',
    userName: 'Admin User',
    timestamp: new Date().toISOString(),
    changes: [{ field: 'email', oldValue: null, newValue: 'new@example.com' }],
    ipAddress: '192.168.1.1',
    userAgent: 'Chrome/120.0',
  },
  {
    id: '2',
    action: 'update',
    entityType: 'settings',
    entityId: 's1',
    userId: 'admin1',
    userName: 'Admin User',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    changes: [{ field: 'theme', oldValue: 'light', newValue: 'dark' }],
    ipAddress: '192.168.1.1',
    userAgent: 'Chrome/120.0',
  },
  {
    id: '3',
    action: 'delete',
    entityType: 'api_key',
    entityId: 'ak456',
    userId: 'user2',
    userName: 'John Doe',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    changes: [],
    ipAddress: '10.0.0.5',
    userAgent: 'Firefox/121.0',
  },
  {
    id: '4',
    action: 'view',
    entityType: 'report',
    entityId: 'r789',
    userId: 'user3',
    userName: 'Jane Smith',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    changes: [],
    ipAddress: '172.16.0.10',
    userAgent: 'Safari/17.0',
  },
];

export const auditService = {
  /**
   * List audit entries with optional filters
   */
  async list(params?: {
    action?: string;
    entityType?: string;
    userId?: string;
    startDate?: string;
    endDate?: string;
    page?: number;
    limit?: number;
  }): Promise<AuditEntry[]> {
    if (config.enableMockData) {
      await simulateApiDelay();
      
      let filtered = [...mockAuditEntries];
      
      if (params?.action) {
        filtered = filtered.filter((e) => e.action === params.action);
      }
      if (params?.entityType) {
        filtered = filtered.filter((e) => e.entityType === params.entityType);
      }
      if (params?.userId) {
        filtered = filtered.filter((e) => e.userId === params.userId);
      }
      if (params?.startDate) {
        filtered = filtered.filter((e) => new Date(e.timestamp) >= new Date(params.startDate!));
      }
      if (params?.endDate) {
        filtered = filtered.filter((e) => new Date(e.timestamp) <= new Date(params.endDate!));
      }
      
      return filtered;
    }

    try {
      return await endpoints.audit.list(params) as AuditEntry[];
    } catch (error) {
      console.error('[auditService] Failed to fetch audit entries:', error);
      throw new Error('Failed to load audit logs from server');
    }
  },

  /**
   * Get audit entry by ID
   */
  async get(id: string): Promise<AuditEntry> {
    if (config.enableMockData) {
      await simulateApiDelay();
      const entry = mockAuditEntries.find((e) => e.id === id);
      if (!entry) {
        throw new Error('Audit entry not found');
      }
      return { ...entry };
    }

    try {
      return await endpoints.audit.get(id);
    } catch (error) {
      console.error(`[auditService] Failed to fetch audit entry ${id}:`, error);
      throw new Error('Failed to load audit entry details');
    }
  },

  /**
   * Create new audit entry (manual logging)
   */
  async create(data: Omit<AuditEntry, 'id' | 'timestamp'>): Promise<AuditEntry> {
    if (config.enableMockData) {
      await simulateApiDelay();
      const newEntry: AuditEntry = {
        ...data,
        id: crypto.randomUUID(),
        timestamp: new Date().toISOString(),
      };
      mockAuditEntries.unshift(newEntry);
      return { ...newEntry };
    }

    try {
      // Note: Backend may not support manual audit entry creation
      // This would typically be auto-generated by the system
      throw new Error('Manual audit entry creation not supported by backend');
    } catch (error) {
      console.error('[auditService] Failed to create audit entry:', error);
      throw error;
    }
  },

  /**
   * Update audit entry (for corrections)
   * Note: In production, audit logs should be immutable
   */
  async update(id: string, data: Partial<AuditEntry>): Promise<AuditEntry> {
    if (config.enableMockData) {
      await simulateApiDelay();
      const index = mockAuditEntries.findIndex((e) => e.id === id);
      if (index === -1) {
        throw new Error('Audit entry not found');
      }

      mockAuditEntries[index] = { ...mockAuditEntries[index], ...data };
      return { ...mockAuditEntries[index] };
    }

    try {
      // Note: Production audit logs should be immutable
      throw new Error('Audit entry updates not supported (immutable logs)');
    } catch (error) {
      console.error(`[auditService] Failed to update audit entry ${id}:`, error);
      throw error;
    }
  },

  /**
   * Delete audit entry (soft delete with logging)
   */
  async delete(id: string): Promise<void> {
    if (config.enableMockData) {
      await simulateApiDelay();
      const index = mockAuditEntries.findIndex((e) => e.id === id);
      if (index === -1) {
        throw new Error('Audit entry not found');
      }

      // Create meta-audit entry for the deletion
      const deletionEntry: AuditEntry = {
        id: crypto.randomUUID(),
        action: 'delete',
        entityType: 'audit_entry',
        entityId: id,
        userId: 'current_user',
        userName: 'Admin User',
        timestamp: new Date().toISOString(),
        changes: [
          {
            field: 'deleted',
            oldValue: false,
            newValue: true,
          },
        ],
        ipAddress: '127.0.0.1',
        userAgent: navigator.userAgent,
      };

      mockAuditEntries.splice(index, 1);
      mockAuditEntries.unshift(deletionEntry);
      return;
    }

    try {
      // Note: Production may implement soft delete or prevent deletion entirely
      throw new Error('Audit entry deletion not supported (compliance requirement)');
    } catch (error) {
      console.error(`[auditService] Failed to delete audit entry ${id}:`, error);
      throw error;
    }
  },
};
